B.pyoを作りました#1
cyuze/gitremote2 pull request #6
Opened 2024-10-31 03:32 UTC by SatoShunta

レビューをお願いします
close #1

2024-10-31 03:35 UTC, cyuze commented on B.py
> +def hallo():
helloのスペルが違います

2024-10-31 03:40 UTC, cyuze requested changes
オーケーです

2024-10-31 03:40 UTC, cyuze commented on B.py
> +def hallo():
```suggestion
def hello():
```
こうするべきです。べぇい

2024-11-01 02:24 UTC, cyuze approved these changes
おっけいです

2024-11-01 02:25 UTC, sugar-yuki approved these changes
ok

2024-11-01 02:26 UTC, merged